id: A5002D064
title: A Short Prayer to Chöying Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:40:03.389175
  last_modified_at: 2022-02-28 22:40:03.389182
