id: A5002D064
title: A Prayer to Mañjuśrī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:40:03.385164
  last_modified_at: 2022-02-28 22:40:03.385171
